platform :ios, '7.0'
pod "AFNetworking", "~> 2.5.4"

pod 'MBProgressHUD', '~> 0.9.1'

platform :ios, '6.1'
pod 'SDWebImage', '~>3.7'

pod 'MJRefresh'

pod 'MJExtension'

pod 'SVProgressHUD'

pod "Toast", "~> 2.4"